/*
Empresa LeadTech

Banco de dados relacionado a app de Java - LookBooks MVC

Bianca Leticia Román Caldeira - RM552267 - Turma : 2TDSPH
Charlene Aparecida Estevam Mendes Fialho - RM552252 - Turma : 2TDSPH
Lais Alves Da Silva Cruz - RM:552258 - Turma : 2TDSPH
Fabrico Torres Antonio - RM:97916 - Turma : 2TDSPH
Lucca Raphael Pereira dos Santos - RM 99675 - Turma : 2TDSPZ 

------------------ ESSE SCRIPT CONTEM OS DDL E OS DEMAIS SOLICITADOS EM DEVOPS PARA DEPLOY NO AZURE ------------------

*/

/*DROPS*/
DROP TABLE clothing_item CASCADE CONSTRAINTS;
DROP TABLE lookbook CASCADE CONSTRAINTS;
DROP TABLE lookbook_clothing_item CASCADE CONSTRAINTS;

-- DDL para tabela clothing_item
CREATE TABLE clothing_item (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_cadastro DATE,
    preco FLOAT(53) NOT NULL,
    categoria VARCHAR2(255 CHAR) NOT NULL CHECK (categoria IN ('CAMISETA', 'CALCA', 'VESTIDO', 'JAQUETA', 'SAIA', 'SHORTS', 'SUETER', 'CAMISA', 'JAQUETA_CASACO', 'CONJUNTO')),
    cor VARCHAR2(255 CHAR) NOT NULL,
    imagem_url VARCHAR2(255 CHAR),
    marca VARCHAR2(255 CHAR) NOT NULL,
    material VARCHAR2(255 CHAR) NOT NULL,
    nome VARCHAR2(255 CHAR) NOT NULL,
    padrao VARCHAR2(255 CHAR) NOT NULL CHECK (padrao IN ('LISTRADO', 'FLORAL', 'XADREZ', 'POA', 'LISO', 'ABSTRATO', 'GEOMETRICO', 'ANIMAL_PRINT', 'ESTAMPADO')),
    sazonalidade VARCHAR2(255 CHAR) NOT NULL CHECK (sazonalidade IN ('VERÃO', 'INVERNO', 'PRIMAVERA', 'OUTONO')),
    tamanho VARCHAR2(255 CHAR) NOT NULL CHECK (tamanho IN ('PP', 'P', 'M', 'G', 'GG', 'XG'))
    -- Comentário: Tabela de itens de vestuário.
    -- Chave primária: id
);

-- DDL para tabela lookbook
CREATE TABLE lookbook (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_criacao DATE,
    nome VARCHAR2(255 CHAR) NOT NULL
    -- Comentário: Tabela de lookbooks.
    -- Chave primária: id
);

-- DDL para tabela de relacionamento lookbook_clothing_item
CREATE TABLE lookbook_clothing_item (
    clothing_item_id NUMBER(19, 0) NOT NULL,
    lookbook_id NUMBER(19, 0) NOT NULL,
    CONSTRAINT fk_clothing_item FOREIGN KEY (clothing_item_id) REFERENCES clothing_item (id),
    CONSTRAINT fk_lookbook FOREIGN KEY (lookbook_id) REFERENCES lookbook (id),
    PRIMARY KEY (clothing_item_id, lookbook_id)
    -- Comentário: Tabela de relacionamento entre lookbooks e itens de vestuário.
    -- Chave primária: clothing_item_id, lookbook_id
);

-- 5 INSERTS EM CADA TABELA
/* TABELA: clothing_item*/
- Peca de Roupa 1
INSERT INTO clothing_item (nome, categoria, cor, tamanho, imagem_url, material, marca, padrao, preco, data_cadastro, sazonalidade) VALUES ('Camiseta Branca', 'CAMISETA', 'Branco', 'M', 'https://abrir.link/DwOYl', 'Algodao', 'Nike', 'LISO', 49.90, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 'VERAO');

-- Peca de Roupa 2
INSERT INTO clothing_item (nome, categoria, cor, tamanho, imagem_url, material, marca, padrao, preco, data_cadastro, sazonalidade) VALUES ('Vestido Floral', 'VESTIDO', 'Azul', 'P', 'https://abrir.link/xmZnn', 'Poliester', 'Zara', 'FLORAL', 129.90, TO_DATE('2024-08-15', 'YYYY-MM-DD'), 'PRIMAVERA');

-- Peca de Roupa 3
INSERT INTO clothing_item (nome, categoria, cor, tamanho, imagem_url, material, marca, padrao, preco, data_cadastro, sazonalidade) VALUES ('Calca Jeans', 'CALCA', 'Azul', 'G', 'https://abrir.link/AnnAE', 'Jeans', 'Lee', 'LISO', 99.90, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 'OUTONO');

-- Peca de Roupa 4
INSERT INTO clothing_item (nome, categoria, cor, tamanho, imagem_url, material, marca, padrao, preco, data_cadastro, sazonalidade) VALUES ('Jaqueta de Couro', 'JAQUETA', 'Preto', 'M', 'https://abrir.link/cFHDB', 'Couro', 'Guess', 'LISO', 299.90, TO_DATE('2024-09-05', 'YYYY-MM-DD'), 'INVERNO');

-- Peça de Roupa 5
INSERT INTO clothing_item (nome, categoria, cor, tamanho, imagem_url, material, marca, padrao, preco, data_cadastro, sazonalidade) VALUES ('Camisa Social', 'CAMISA', 'Azul Escuro', 'G', 'https://abrir.link/OloiE', 'Algodao', 'Polo', 'LISO', 89.90, TO_DATE('2024-08-25', 'YYYY-MM-DD'), 'OUTONO');

/* TABELA: lookbook*/
-- Lookbook 1
INSERT INTO lookbook (nome, data_criacao) VALUES ('Look Verao Casual', TO_DATE('2024-09-04', 'YYYY-MM-DD'));

-- Lookbook 2
INSERT INTO lookbook (nome, data_criacao) VALUES ('Look Primavera Romantico', TO_DATE('2024-09-01', 'YYYY-MM-DD'));

-- Lookbook 3
INSERT INTO lookbook (nome, data_criacao) VALUES ('Look Casual de Outono', TO_DATE('2024-08-20', 'YYYY-MM-DD'));

-- Lookbook 4
INSERT INTO lookbook (nome, data_criacao) VALUES ('Look Inverno Urbano', TO_DATE('2024-09-06', 'YYYY-MM-DD'));

-- Lookbook 5
INSERT INTO lookbook (nome, data_criacao) VALUES ('Look Festa Chic', TO_DATE('2024-09-10', 'YYYY-MM-DD'));

/* TABELA: lookbook_clothing_item */
-- Relacionando Lookbook 1 com Clothing Item 1 (Camiseta Branca)
INSERT INTO lookbook_clothing_item (lookbook_id, clothing_item_id) VALUES (1, 1);


-- Relacionando Lookbook 2 com Clothing Item 2 (Vestido Floral)
INSERT INTO lookbook_clothing_item (lookbook_id, clothing_item_id) VALUES (2, 2);

-- Relacionando Lookbook 3 com Clothing Item 3 (Calca Jeans)
INSERT INTO lookbook_clothing_item (lookbook_id, clothing_item_id) VALUES (3, 3);

-- Relacionando Lookbook 4 com Clothing Item 4 (Jaqueta de Couro)
INSERT INTO lookbook_clothing_item (lookbook_id, clothing_item_id) VALUES (4, 4);

-- Relacionando Lookbook 5 com Clothing Item 5 (Camisa Social)
INSERT INTO lookbook_clothing_item (lookbook_id, clothing_item_id) VALUES (5, 5);

-- Confirmando alterações
COMMIT;

-- Consultando todos os dados da tabelas
SELECT * FROM clothing_item;
SELECT * FROM lookbook;
SELECT * FROM lookbook_clothing_item;
